In [3]:
import pandas as pd
import requests

In [ ]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2025&competition_frame_ids=1&competition_ids=589&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()

tables = pd.read_html(resp.text)
df_2024 = tables[0]
print(df_2024.head())

In [4]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2024&competition_frame_ids=1&competition_ids=589&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()

tables = pd.read_html(resp.text)
df_2024 = tables[0]
print(df_2024.head())

   シーズン  大会       節            試合日  K/O時刻  ホーム  スコア アウェイ スタジアム   入場者数  \
0  2024  Ｊ１  第１節第１日  24/02/23(金・祝)  14:06   広島  2-0   浦和  Ｅピース  27545
1  2024  Ｊ１  第１節第１日  24/02/23(金・祝)  18:03  名古屋  0-3   鹿島   豊田ス  36933
2  2024  Ｊ１  第１節第２日    24/02/24(土)  13:03   磐田  0-2   神戸   ヤマハ  14778
3  2024  Ｊ１  第１節第２日    24/02/24(土)  14:04   福岡  0-0   札幌  ベススタ   9445
4  2024  Ｊ１  第１節第２日    24/02/24(土)  14:05   鳥栖  1-2   新潟   駅スタ   9610

     インターネット中継・TV放送
0        ＤＡＺＮ／ＮＨＫ総合
1              ＤＡＺＮ
2         ＤＡＺＮ／静岡放送
3  ＤＡＺＮ／ＮＨＫ福岡／ＮＨＫ札幌
4  ＤＡＺＮ／ＮＨＫ新潟／サガテレビ

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/1911878067.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [5]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2023&competition_frame_ids=1&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2023 = tables[0]
print(df_2023.head())

   シーズン  大会       節          試合日  K/O時刻   ホーム  スコア  アウェイ スタジアム   入場者数  \
0  2023  Ｊ１  第１節第１日  23/02/17(金)  19:04   川崎Ｆ  1-2  横浜FM   等々力  22563
1  2023  Ｊ１  第１節第２日  23/02/18(土)  14:03  横浜FC  0-1   名古屋  ニッパツ  11186
2  2023  Ｊ１  第１節第２日  23/02/18(土)  14:03    京都  0-2    鹿島  サンガＳ  15988
3  2023  Ｊ１  第１節第２日  23/02/18(土)  14:03    広島  0-0    札幌   Ｅスタ  13121
4  2023  Ｊ１  第１節第２日  23/02/18(土)  14:03  FC東京  2-0    浦和   味スタ  38051

           インターネット中継・TV放送
0                    ＤＡＺＮ
1  ＤＡＺＮ／ＮＨＫ名古屋／ＮＨＫ岐阜／ＮＨＫ津
2     ＤＡＺＮ／ＮＨＫ京都／ＫＢＳ京都（録）
3              ＤＡＺＮ／ＮＨＫ広島
4              ＤＡＺＮ／ＮＨＫ総合

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/3555828033.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [25]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2022&competition_frame_ids=1&competition_ids=521&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2022 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/461758500.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [26]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2021&competition_frame_ids=1&competition_ids=492&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2021 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/1096377586.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [27]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2020&competition_frame_ids=1&competition_ids=477&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2020 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/1099686557.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [29]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2019&competition_frame_ids=1&competition_ids=460&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2019 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/2328571828.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [31]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2018&competition_frame_ids=1&competition_ids=444&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2018 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/2500422311.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [32]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2017&competition_frame_ids=1&competition_ids=428&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2017 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/2717200579.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [33]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2016&competition_frame_ids=1&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2016 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/1642157841.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [34]:
url = "https://data.j-league.or.jp/SFMS01/search?competition_years=2015&competition_frame_ids=1&tv_relay_station_name="
headers = {"User-Agent": "Mozilla/5.0"}
resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()
tables = pd.read_html(resp.text)
df_2015 = tables[0]

/var/folders/5s/tm2tnv153l5gfqlv4g_q9dqw0000gn/T/ipykernel_88494/439094985.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(resp.text)

In [35]:
# df結合
df = pd.concat([df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021, df_2022, df_2023, df_2024])
df

,シーズン,大会,節,試合日,K/O時刻,ホーム,スコア,アウェイ,スタジアム,入場者数,インターネット中継・TV放送
0,2015,Ｊ１ １ｓｔ,第１節第１日,15/03/07(土),14:04,名古屋,3-3,松本,豊田ス,33558,スカパー！／スカパー！プレミアムサービス／ＮＨＫ名古屋／ＮＨＫ長野／ＮＨＫ岐阜／ＮＨＫ津
1,2015,Ｊ１ １ｓｔ,第１節第１日,15/03/07(土),14:04,Ｇ大阪,2-2,FC東京,万博,18332,スカパー！／スカパー！プレミアムサービス／ＮＨＫ総合
2,2015,Ｊ１ １ｓｔ,第１節第１日,15/03/07(土),14:04,広島,2-0,甲府,Ｅスタ,14671,スカパー！／スカパー！プレミアムサービス／ＮＨＫ広島／ＮＨＫ甲府
3,2015,Ｊ１ １ｓｔ,第１節第１日,15/03/07(土),14:05,鳥栖,2-1,新潟,ベアスタ,11580,スカパー！／スカパー！プレミアムサービス／ＮＨＫ佐賀／ＮＨＫ新潟
4,2015,Ｊ１ １ｓｔ,第１節第１日,15/03/07(土),14:05,仙台,2-0,山形,ユアスタ,19375,スカパー！／スカパー！プレミアムサービス／ＮＨＫ仙台／ＮＨＫ山形／ＮＨＫ青森／ＮＨＫ岩手／Ｎ...
...,...,...,...,...,...,...,...,...,...,...,...
375,2024,Ｊ１,第３８節第１日,24/12/08(日),14:03,横浜FM,0-2,名古屋,日産ス,42866,ＤＡＺＮ
376,2024,Ｊ１,第３８節第１日,24/12/08(日),14:03,札幌,1-0,柏,プレド,21721,ＤＡＺＮ／ＮＨＫ札幌
377,2024,Ｊ１,第３８節第１日,24/12/08(日),14:03,鹿島,3-1,町田,カシマ,32840,ＤＡＺＮ
378,2024,Ｊ１,第３８節第１日,24/12/08(日),14:04,神戸,3-0,湘南,ノエスタ,27444,ＤＡＺＮ／サンテレビ／ＮＨＫ総合
379,2024,Ｊ１,第３８節第１日,24/12/08(日),14:04,浦和,0-0,新潟,埼玉,55184,ＤＡＺＮ／テレ玉

In [37]:
# ホームFC東京のみ抽出
df_tokyo_home = df[df['ホーム'] == 'FC東京']
df_tokyo_home = df_tokyo_home.reset_index(drop=True)
df_tokyo_home

,シーズン,大会,節,試合日,K/O時刻,ホーム,スコア,アウェイ,スタジアム,入場者数,インターネット中継・TV放送
0,2015,Ｊ１ １ｓｔ,第２節第２日,15/03/14(土),14:06,FC東京,0-0,横浜FM,味スタ,30492,スカパー！／スカパー！プレミアムサービス／ＴＢＳ／ＴＯＫＹＯ ＭＸ（録）
1,2015,Ｊ１ １ｓｔ,第４節第２日,15/04/04(土),16:03,FC東京,1-0,甲府,味スタ,20743,スカパー！／スカパー！プレミアムサービス
2,2015,Ｊ１ １ｓｔ,第６節第２日,15/04/18(土),16:03,FC東京,1-2,広島,味スタ,24369,スカパー！／スカパー！プレミアムサービス／ＴＯＫＹＯ ＭＸ（録）
3,2015,Ｊ１ １ｓｔ,第９節第１日,15/05/02(土),16:04,FC東京,2-1,川崎Ｆ,味スタ,42604,スカパー！／スカパー！プレミアムサービス
4,2015,Ｊ１ １ｓｔ,第１１節第１日,15/05/10(日),16:04,FC東京,0-1,鹿島,味スタ,42070,スカパー！／スカパー！プレミアムサービス
...,...,...,...,...,...,...,...,...,...,...,...
169,2024,Ｊ１,第２７節第２日,24/08/17(土),19:03,FC東京,0-0,東京Ｖ,味スタ,39921,ＤＡＺＮ／ＴＯＫＹＯ ＭＸ
170,2024,Ｊ１,第３０節第２日,24/09/14(土),19:04,FC東京,4-1,名古屋,国立,55896,ＤＡＺＮ
171,2024,Ｊ１,第３３節第２日,24/10/05(土),15:03,FC東京,1-1,鳥栖,味スタ,21140,ＤＡＺＮ
172,2024,Ｊ１,第３５節第４日,24/11/03(日・祝),14:03,FC東京,0-2,湘南,味スタ,28337,ＤＡＺＮ／テレビ東京（録）
173,2024,Ｊ１,第３８節第１日,24/12/08(日),14:03,FC東京,3-0,Ｃ大阪,味スタ,32787,ＤＡＺＮ

In [38]:
df_tokyo_home.to_csv('J1_tokyo_home_2015-2024.csv', index=False)